--
-- Table structure for table `#__dory_documents` 
--

CREATE TABLE IF NOT EXISTS `#__dory_documents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `downloads` int NOT NULL DEFAULT 0,
  `state` tinyint NOT NULL DEFAULT 0,
  `catid` int unsigned NOT NULL DEFAULT 0,
  `description` text NOT NULL,
--  `sticky` tinyint unsigned NOT NULL DEFAULT 0,
  `ordering` int NOT NULL DEFAULT 0,
--  `metakey` text NOT NULL,
--  `params` text NOT NULL,
--  `own_prefix` tinyint NOT NULL DEFAULT 0,
--  `metakey_prefix` varchar(400) NOT NULL DEFAULT '',
--  `purchase_type` tinyint NOT NULL DEFAULT -1,
--  `track_clicks` tinyint NOT NULL DEFAULT -1,
--  `track_impressions` tinyint NOT NULL DEFAULT -1,
  `checked_out` int unsigned,
  `checked_out_time` datetime,
  `publish_up` datetime,
  `publish_down` datetime,
  `reset` datetime,
  `created` datetime NOT NULL,
  `language` char(7) NOT NULL DEFAULT '',
  `created_by` int unsigned NOT NULL DEFAULT 0,
  `created_by_alias` varchar(255) NOT NULL DEFAULT '',
  `modified` datetime NOT NULL,
  `modified_by` int unsigned NOT NULL DEFAULT 0,
  `version` int unsigned NOT NULL DEFAULT 1,
	`access` INT NOT NULL,
	`access_users` VARCHAR(255),
	`access_usergroups` VARCHAR(255),
	`file_name` VARCHAR(255) NOT NULL,
	`file_path` VARCHAR(255) NOT NULL,
	`file_md5` VARCHAR(32) NOT NULL,
	`file_size` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_state` (`state`),
--  KEY `idx_own_prefix` (`own_prefix`),
--  KEY `idx_metakey_prefix` (`metakey_prefix`(100)),
  KEY `idx_document_catid` (`catid`),
  KEY `idx_language` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;